### ISSUE TITLE
Adding DelosMiner 1.2.1 32-bit and 64-bit

### ISSUE THREAD

**Issue by centreece** [All-in-Miner/All-in-Miner#1]
Could you consider to add both, the 32-bit and the 64-bit version of Delos?

> Notes: 32-bit version might perform faster for certain algorithms.

[Source](https://bitcointalk.org/index.php?topic=4344544.0)

**Comment by All-in-Miner** [comment]
64-bit version of Delos and Delos-x16r is added.

32-bit version will be added once I know which algo is supposed to perform better with 32-bit! ;)
