### ISSUE TITLE
Adding Ravencoin Miner 3.1

### ISSUE THREAD

**Issue by centreece** [All-in-Miner/All-in-Miner#2]
Could you add the latest release?

with Cuda 9.2: https://github.com/RavencoinProject/RavencoinMiner/releases/tag/v3.1-cu92
with Cuda 9.1: https://github.com/RavencoinProject/RavencoinMiner/releases/tag/v3.1-cu91

**Comment by All-in-Miner** [comment]
Sure. Any idea if the CUDA 9.2 release is significantly faster?

**Comment by All-in-Miner** [comment]
Test complete!

CUDA 9.2 version is faster. Added!
